#!/usr/bin/env bash

set -euo pipefail

project_name="general"

script_dir=$(dirname $(readlink -f $0))
base_dir=$(git rev-parse --show-toplevel 2>/dev/null || pwd)

image_source_files=(
  Dockerfile
  entrypoint.sh
  entrypoint-user.sh
)
image_source_mtime=$(
  for file in ${image_source_files[@]}; do
    stat -c %Y $script_dir/$file
  done \
  | sort -nr | head -n1
)

image_name="$project_name-devshell:latest"
need_to_build=true

if [[ -n $(docker images -q $image_name) ]]; then
  image_mtime=$(docker image inspect $image_name | jq ".[0].Created" | xargs date +%s -d)
  if [[ $image_mtime -gt $image_source_mtime ]]; then
    need_to_build=false
  fi
fi

if $need_to_build; then
  echo "Building docker image..."
  docker build -t $image_name $script_dir
fi

docker_opts=${DEVSHELL_DOCKER_OPTS:-"-it"}

if [[ -d ${HOME}/.zprezto ]]; then
  docker_opts="${docker_opts} \
    --volume ${HOME}/.zprezto:/usr/local/lib/prezto:ro"
fi

exec docker run --rm $docker_opts \
  --volume $base_dir:$base_dir \
  --volume ${project_name}-devshell-home:/home/user \
  --env TERM=$TERM \
  --env HOST_PROJECT_DIR=$base_dir \
  ${project_name}-devshell \
  "$@"
