#!/usr/bin/env bash

set -euo pipefail

project_name="new-project"

script_dir=$(dirname $(readlink -f $0))
base_dir=$(git rev-parse --show-toplevel)

image_source_files=(
  Dockerfile
  entrypoint.sh
  entrypoint-user.sh
)
image_source_mtime=$(
  for file in ${image_source_files[@]}; do
    stat -c %Y $script_dir/$file
  done \
  | sort -nr | head -n1
)

image_name="$project_name-dev:latest"
need_to_build=true

if [[ -n $(docker images -q $image_name) ]]; then
  image_mtime=$(docker image inspect $image_name | jq ".[0].Created" | xargs date +%s -d)
  if [[ $image_mtime -gt $image_source_mtime ]]; then
    need_to_build=false
  fi
fi

if $need_to_build; then
  echo "Building docker image..."
  docker build -t $image_name $script_dir
fi

docker_opts=${DEVSHELL_DOCKER_OPTS:-"-it"}

exec docker run --rm $docker_opts \
  --volume $base_dir:$base_dir \
  --volume ~/.zprezto:/usr/local/lib/prezto:ro \
  --volume ${project_name}-dev-home:/home/user \
  --env HOST_PROJECT_DIR=$base_dir \
  ${project_name}-dev \
  "$@"
