FROM alpine AS dev

# ASDF
RUN apk add --no-cache --virtual .asdf go \
  && GOBIN=/usr/local/bin go install github.com/asdf-vm/asdf/cmd/asdf@latest \
  && apk del .asdf \
  && rm -rf /root/.cache \
  && rm -rf /root/.config \
  && rm -rf /root/go

RUN apk add --no-cache \
  bash \
  coreutils \
  curl \
  git \
  shadow \
  sudo \
  util-linux \
  zsh \
  zsh-vcs

COPY entrypoint.sh /usr/local/bin
COPY entrypoint-user.sh /usr/local/bin

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
