FROM alpine AS dev

RUN apk add --no-cache \
  coreutils \
  bash \
  git \
  shadow \
  sudo \
  util-linux \
  zsh \
  zsh-vcs

COPY entrypoint.sh /usr/local/bin
COPY entrypoint-user.sh /usr/local/bin

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/bin/zsh"]
